In [40]:
import pandas as pd
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [41]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [42]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [43]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent=dataset[['charges']]

In [44]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid={'criterion':['squared_error','friedman_mse','absolute_error','poisson'],
            'max_features':['sqrt','log2'],
            'n_estimators':[10,100]}
grid=GridSearchCV(RandomForestRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

C:\Anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [45]:
re=grid.cv_results_
rscore=grid.best_params_
print(f"The R_score value for best parameter:{rscore}")

The R_score value for best parameter:{'criterion': 'friedman_mse', 'max_features': 'log2', 'n_estimators': 100}

In [46]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.088541,0.019361,0.007228,0.001972,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.834697,0.767364,0.846795,0.807189,0.816118,0.814433,0.027309,15
1,0.400428,0.012722,0.018170,0.001291,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.858074,0.782073,0.862187,0.829136,0.838596,0.834013,0.028689,4
2,0.070331,0.021788,0.005731,0.000874,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.834168,0.764278,0.823349,0.809017,0.829139,0.811990,0.025299,16
3,0.349465,0.003237,0.017656,0.000701,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.858076,0.778475,0.861258,0.827537,0.841022,0.833274,0.029980,5
4,0.040077,0.001747,0.005092,0.000294,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.843484,0.751825,0.841920,0.806107,0.844123,0.817492,0.035842,12
5,0.339299,0.004450,0.020313,0.002188,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.856157,0.781132,0.861967,0.829125,0.843429,0.834362,0.028914,3
6,0.038910,0.001771,0.004887,0.000282,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.845639,0.779294,0.851488,0.813416,0.831406,0.824249,0.026035,9
7,0.340618,0.002907,0.018017,0.000708,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.857817,0.781220,0.861847,0.831097,0.841426,0.834681,0.028947,1
8,0.137325,0.005506,0.004649,0.000387,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.849244,0.762015,0.825092,0.817872,0.831078,0.817060,0.029419,13
9,1.222631,0.114902,0.014634,0.002144,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.859723,0.777406,0.849734,0.830225,0.844871,0.832392,0.029092,8
10,0.134436,0.003474,0.005477,0.000824,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.840564,0.759821,0.839049,0.830653,0.824428,0.818903,0.030114,10
11,1.218897,0.067452,0.013913,0.001835,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.854714,0.778598,0.855182,0.830113,0.845778,0.832877,0.028617,6
12,0.043054,0.001315,0.005469,0.000917,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.841658,0.758143,0.844038,0.822994,0.821749,0.817716,0.031174,11
13,0.370644,0.005364,0.019103,0.002280,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.858190,0.780750,0.861537,0.826443,0.836095,0.832603,0.029089,7
14,0.040873,0.001081,0.004808,0.000769,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.834085,0.752819,0.848421,0.807466,0.837945,0.816147,0.034422,14
15,0.357549,0.015882,0.018709,0.001918,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.860041,0.781175,0.862814,0.826680,0.842201,0.834582,0.029725,2

In [32]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
Future_Prediction

Age: 35
BMI: 35
Children: `

ValueError: could not convert string to float: '`'